#!/bin/bash

passwd_file=$(cat /etc/passwd); while read -r line; do username=$(echo "$line" | cut -d ':' -f 1);home_dir=$(echo "$line" | cut -d ':' -f 6);echo "${username}:${home_dir}";done <<< "$passwd_file" | sort

